server:
  port: 8089
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    # 使用Microsoft JDBC驱动 + SQL Server身份验证
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://DESKTOP-SOU1KQ1;databaseName=ryl_engineer;encrypt=true;trustServerCertificate=true
    username: sa
    password: zxcv1234
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    user:
      name: disabled
      password: none
  # Flyway配置
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: false
    out-of-order: true
    clean-disabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ryl.engineer.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # SQL Server特定配置
  config-location: classpath:mybatis-config.xml

logging:
  level:
    com.ryl.engineer: debug
    org.springframework.web: warn
    org.mybatis: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

# JWT配置
jwt:
  # 密钥
  secret: ryl-engineer-secret-key
  # 过期时间（秒）
  expiration: 86400

# 统一文件上传配置
ryl:
  file:
    upload-path: D:/servers/ryl-engineer/uploads # 上传文件存储物理根路径
    url-prefix: http://localhost:8089 # 对外访问的URL前缀, 注意这里不包含 /api/v1

# SpringDoc OpenAPI配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

