spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=ryl_engineer;encrypt=false
    username: sa
    password: zxcv1234
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      pool-name: RylHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    
logging:
  level:
    com.ryl.miniprogram: info
    org.springframework.web: warn
    org.mybatis: warn 